modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="crucible"
version="1.0.0"
displayName="Crucible"
logoFile="logo.png"
authors="Charmander906"
description='''Reworks the armor progression system to encourage slower, more methodical gameplay. Works best with a high difficulty.'''
[[dependencies.crucible]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.0,47.2.0)"
    ordering="NONE"
    side="BOTH"
[[dependencies.crucible]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"